version: "3.7"

services:
    db:
        container_name: db
        image: postgres:15rc1
        networks:
            - cms
        ports:
            - ${DB_PORT}
        volumes:
            - db:/var/lib/postgres
            - ./libs/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    proxy:
        container_name: proxy
        image: nginx:1.23.1-alpine
        restart: always
        networks:
            - cms
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./libs/proxy/conf.d:/etc/nginx/conf.d
    core:
        container_name: core
        env_file:
            - apps/core/.env
        build:
            context: .
            dockerfile: apps/core/Dockerfile
        networks:
            - cms
        restart: always
        ports:
            - 4000
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: apps/frontend/Dockerfile
        networks:
            - cms
        restart: always
        ports:
            - 3000

volumes:
    db:
networks:
    cms:
