version: "3.7"

services:
    db:
        container_name: db
        networks:
            - db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db:/var/lib/mysql
        restart: always
    cache:
        container_name: cache
        image: redis
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - redis:/var/lib/redis
    proxy:
        container_name: proxy
        image: richarvey/nginx-php-fpm
        restart: always
        depends_on:
            - db
        ports:
            - 3333:80
        volumes:
            - type: bind
              source: ./apps/api
              target: /apps/api
            - type: bind
              source: ./libs/proxy/sites-enabled
              target: /etc/nginx/sites-enabled
    adminer:
        container_name: adminer
        networks:
            - db
        image: adminer
        restart: always
        ports:
            - 4444:8080

volumes:
    db:
        name: db
    redis:
        name: cache
networks:
    db:
        name: db
